# Generated by Django 4.0.4 on 2022-05-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Payment',
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_period',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('TRIMESTRIAL', 'TRIMESTRIAL'), ('ANNUAL', 'ANNUAL')], default='TRIMESTRIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('StemQuest Program', 'StemQuest Program'), ('On Choice Camps', 'On Choice Camps'), ('Holidays Camps', 'Holidays Camps')], default='StemQuest Program', max_length=25),
        ),
    ]
