# Generated by Django 4.0.4 on 2022-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_registration_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
