# Generated by Django 4.0.4 on 2022-05-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inscription_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='title',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='program',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.CharField(default='younes', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student_Parent',
        ),
    ]
