# Generated by Django 4.0.4 on 2022-05-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_school_payment_abonnement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
