# Generated by Django 4.0.4 on 2022-05-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='membership',
        ),
    ]
