# Generated by Django 4.0.4 on 2022-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='payment/'),
        ),
    ]
