# Generated by Django 4.0.4 on 2022-07-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
